---
title: "Course1_getting_started"
author: "Roxana Agrigoroaie"
date: "April 22, 2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction to Shiny

Shiny - R package that allows us to create a web application using R code.

A web app is made up of UI and a server. It is updated based on user input/interaction. 

Sometimes it can be useful for a data analyst/scientist to turn his/her analysis into a web application.


## Build a "Hello, world" Shiny app

Parts of a Shiny app:
- load shiny
- create the UI with a HTML function
- define a custom function to create the server
- run the app


To get an input value: textInput(id, label, default); textInput is added in the UI
To display the input value, we use the renderText function in the server side
But only using this, nothing will be displayed on the screen. We need to add a textOutput element in the UI to display our message.

## Build a babynames explorer Shiny app

First, build the sketch of your app. How will it look like and how the user will interact with it. 

For the babynames explorer app: we need an input for the user to pass a name, and the app will display a plot with the popularity of the name over time. A two column layout will be used. We also need to add a title (titlePanel(title)). 

To add the plot we need to include a renderPlot() element in the server. However we also have to include it in the UI with plotOutput(id)


